updated datastream xml files for the test content image
ComplianceAsCode/compliance-operator pull request #163
Opened 2022-10-18 20:15 UTC by Vincent056

There was a regression in the test content image `quay.io/compliance-operator/test-broken-content:kublet_default` on OCP 4.12 cluster, which caused the e2e test to fail. Since we have fix the test image, here we updated the datastream xml files for the test content image.

2022-10-19 17:03 UTC, Vincent056 commented
/retest

2022-10-19 19:17 UTC, rhmdnd commented
This should fix https://github.com/ComplianceAsCode/compliance-operator/issues/164 right?

2022-10-19 19:19 UTC, rhmdnd commented on CHANGELOG.md
> +- There was a regression in `quay.io/compliance-operator/test-broken-content:kublet_default`
Should this be kubelet_default?

2022-10-19 19:20 UTC, Vincent056 commented on CHANGELOG.md
> +- There was a regression in `quay.io/compliance-operator/test-broken-content:kublet_default`
that's correct, let me fix that

2022-10-20 06:26 UTC, JAORMX requested changes
Trivy seems unhappy with a dependency. You need to run:
```
go get -u golang.org/x/text@0.3.8
go mod tidy && go mod verify && go mod vendor
```
To address this.

2022-10-20 09:00 UTC, jhrozek commented
> Trivy seems unhappy with a dependency. You need to run:
> 
> ```
> go get -u golang.org/x/text@0.3.8
> go mod tidy && go mod verify && go mod vendor
> ```
> 
> To address this.

Thanks, I opened  PR #166 to address this. Would you mind acking this so that @Vincent056 can rebase his PR and we can get the release out of the door?

2022-10-20 13:22 UTC, rhmdnd commented
> Thanks, I opened PR #166 to address this. Would you mind acking this so that @Vincent056 can rebase his PR and we can get the release out of the door?

I approved #166. Should be good to rebase this soon.

2022-10-20 15:55 UTC, Vincent056 commented
> > Thanks, I opened PR #166 to address this. Would you mind acking this so that @Vincent056 can rebase his PR and we can get the release out of the door?
> 
> I approved #166. Should be good to rebase this soon.

Thanks for updating this, just rebased the PR here

2022-10-20 18:26 UTC, rhmdnd approved these changes
/lgtm

2022-10-20 18:27 UTC, Vincent056 commented
/px-approved
/qe-approved
/docs-approved

2022-10-20 20:50 UTC, merged