OCPBUGS-1803: Remove compliance_operator_compliance_scan_error_total …
ComplianceAsCode/compliance-operator pull request #223
Opened 2023-02-17 14:31 UTC by rhmdnd

…metric

This metric contained the scan error, which can exceed lenghts of 2k (sometimes 11k), and causes resource issues with Prometheus and integrating metrics into different storage backends.

This commit removes the metric since it goes against Prometheus best practices:

  https://prometheus.io/docs/practices/naming/#labels

2023-02-17 14:34 UTC, sheriff-rh commented on CHANGELOG.md
> +  practices](https://prometheus.io/docs/practices/naming/#labels). This metris
This metric*

2023-02-17 16:51 UTC, Vincent056 commented
Maybe we just need to remove the error message from the metric, instead of completely removing the error metric?

2023-02-17 16:54 UTC, mkumku commented
What exactly does this metric provide? Can you please elaborate a bit more about it?

Before we remove it we should notify the users - ideally set a deprecation note first and then remove next release.
If you want to remove it right now and not follow the process - we need to scope the end user impact: how many users are using it (unsure we have a way to figure it out) but maybe it is an insignificant parameter and can be removed wihtout impacting the production environment.

If we decide  to go the later route, we can issue an internal KCS for Red Hat customers and send a T3 blog to share with the TAMs/CSM to spread the knowledge that way and move on.

2023-02-20 08:51 UTC, JAORMX requested changes
Uhm... is this really the solution? I'd say this really is an issue with the metric's cardinality, and we should instead remove the error message from the metric's labels instead. That would reduce the cardinality greatly. IMO, this is a better solution than removing the metric entirely, as it still gives operators a per-metric view of the error rate in the deployments, as opposed to leaving them in the dark.

I'm not even sure if adding the scan name as metric label is useful. we could probably just have a global error counter.

2023-02-20 09:59 UTC, simonpasquier reviewed
Prometheus developer here, I agree that keeping the metric but removing the high-cardinality labels is probably better than removing it.

2023-02-22 19:28 UTC, rhmdnd commented
Thanks for the feedback - I'll respin this.

2023-02-23 08:01 UTC, xiaojiey commented
/hold for test

2023-02-23 15:41 UTC, JAORMX approved these changes
This looks better IMO. Thanks!

2023-02-23 15:59 UTC, JAORMX commented
/retest

2023-02-23 15:59 UTC, JAORMX commented
@rhmdnd seems you need to update the tests:
```
#11 201.2       inconsistent label cardinality: expected 2 label values but got 1 in prometheus.Labels{"name":"test"}
```

2023-03-01 15:58 UTC, rhmdnd commented
> @rhmdnd seems you need to update the tests:

Fixed, and I have a clean run locally. Need to update the metric to actually remove the error label.

2023-03-07 14:51 UTC, xiaojiey commented
/jira refresh

2023-03-07 14:52 UTC, xiaojiey commented
/jira refresh

2023-03-13 18:15 UTC, rhmdnd commented
/retest

2023-03-17 14:07 UTC, rhmdnd commented
@jhrozek @Vincent056 should be ready for another review from dev.

2023-03-21 14:51 UTC, jhrozek approved these changes
/lgtm

2023-03-22 18:03 UTC, merged