Add bundle script for konflux
ComplianceAsCode/compliance-operator pull request #621
Opened 2024-11-22 07:54 UTC by Vincent056

This will add necessary files needed in order to build bundle for Compliance Operator on Konflux.

2024-11-25 19:51 UTC, yuumasato requested changes

2024-11-25 19:51 UTC, yuumasato commented on bundle-hack/update_csv.py
> +    CO_MUST_GATHER_IMAGE_PULLSPEC = "quay.io/redhat-user-workloads/ocp-isc-tenant/must-gather"
@Vincent056 You can refer to actual builds done in Konflux.

Also, these components should be renamed to include the application name.

2024-11-25 19:51 UTC, yuumasato commented on bundle-hack/update_bundle_annotations.sh
> +echo "$ANNOTATIONS_CONTENT" > ./metadata/annotations.yaml
Nitpick: file without newline at the end.

2024-11-25 19:51 UTC, yuumasato commented on bundle-hack/update_csv.py
> +    main()
Nitpick: file without newline at the end.

2025-01-06 22:03 UTC, rhmdnd commented
@Vincent056 You should be able to rebase this to pickup the dependency updates and get trivy scans passing.

2025-01-08 17:03 UTC, yuumasato approved these changes

2025-01-08 19:12 UTC, yuumasato commented
/retest-required

2025-01-08 22:57 UTC, rhmdnd commented
The e2e-aws-serial tests passed, but failed cleaning up resources in tear down. Unrelated.

2025-01-08 22:58 UTC, merged